import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header/Header";
import PageTransitionWrapper from "@/components/transition/PageTransitionWrapper";
import PageContentWrapper from "@/components/transition/PageContentWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        <PageTransitionWrapper />
        <Header/>
        <PageContentWrapper>
          {children}
        </PageContentWrapper>
      </body>
    </html>
  );
}
